# Generated by Django 5.0.6 on 2024-08-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusinessRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("environment", models.IntegerField()),
                ("investment", models.IntegerField()),
                ("time", models.IntegerField()),
                ("managing_level", models.IntegerField()),
                ("risk_tolerance", models.IntegerField()),
                ("interest", models.IntegerField()),
                ("prefer_working", models.IntegerField()),
                ("work_life_balance", models.IntegerField()),
                ("market", models.IntegerField()),
                ("business_start", models.IntegerField()),
                ("education", models.IntegerField()),
                ("location", models.IntegerField()),
                (
                    "recommended_business",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
